apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-root
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/nsavinda/k8s-test.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/nsavinda/k8s-test.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: express-test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

