apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-test-server
  labels:
    app: express-test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-test-server
  template:
    metadata:
      labels:
        app: express-test-server
    spec:
      containers:
        - name: express-test-server
          image: ghcr.io/nsavinda/express-test-server:latest
          ports:
            - containerPort: 3000
