apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-test-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - example1.com
      secretName: tls-secret-express
  rules:
    - host: example1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: express-test-server
                port:
                  number: 8071
